GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIiwidXNlcklkIjoxLCJpYXQiOjE2NDMxNTI0NDcsImV4cCI6MTY0MzI2MDQ0N30.5SJn2_OWHT5qhLvYWpUWSRR_gKZGdPuVsB6IVpukAho

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email":"user1@gmail.com",
  "password":"user1123"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email":"user4@gmail.com",
  "password":"user4123"
}

###

POST http://localhost:3000/posts/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIiwidXNlcklkIjoxLCJpYXQiOjE2NDMxNTI0NDcsImV4cCI6MTY0MzI2MDQ0N30.5SJn2_OWHT5qhLvYWpUWSRR_gKZGdPuVsB6IVpukAho

{
  "title": "New post",
  "content": "Post content mjaumjgsdtgau1"
}

###

POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIiwidXNlcklkIjoxLCJpYXQiOjE2MTU4NDI3OTYsImV4cCI6MTYxNTg0Mjg1Nn0.yMjSGGjXPNImvQLdPsYPXM3K5ZFRVY6X0zTBIDi1RPw"
}
